name: 👾 Bug report
description: Report an issue with an extension
labels: [bug]
body:
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Before opening a ticket, please go through the following steps.
      options:
        - label: Ensure that your extensions are up-to-date (check the Extensions tab).
          required: true
        - label: Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
          required: true
        - label: If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku) instead.
          required: true
        - label: Write a concise title for this ticket in the field above. 
          required: true

  - type: input
    id: houdoku-version
    attributes:
      label: Houdoku version
      description: |
        Your Houdoku version is listed in the "About" tab.
      placeholder: |
        Example: "2.4.0"
    validations:
      required: true

  - type: input
    id: affected-extensions
    attributes:
      label: Affected extension(s)
      description: |
        Your extension versions are listed in the "Extensions" tab.
      placeholder: |
        Example: "Mangadex 1.2.0, Mangasee 1.1.0"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
