name: 🔮 Feature request
description: Request a feature for an extension
labels: [feature request]
body:
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Before opening a ticket, please go through the following steps.
      options:
        - label: Ensure that your extensions are up-to-date (check the Extensions tab).
          required: true
        - label: Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
          required: true
        - label: If this is an request for Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku) instead.
          required: true
        - label: Write a concise title for this ticket in the field above. 
          required: true

  - type: input
    id: affected-extensions
    attributes:
      label: Affected extension(s)
      description: |
        If this request is for a specific extension, enter it here.
      placeholder: |
        Example: "All"
    validations:
      required: true

  - type: textarea
    id: request-info
    attributes:
      label: Feature request
      description: |
        Describe how you would improve these extensions.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
