name: 🎀 Extension request
description: Request a new extension
labels: [new extension]
body:
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Before opening a ticket, please go through the following steps.
      options:
        - label: Verify that this extension has not already been added (check the Extensions tab).
          required: true
        - label: Check whether there is another ticket requesting this source.
          required: true
        - label: Write a concise title for this ticket in the field above. 
          required: true

  - type: input
    id: source-name
    attributes:
      label: Source name
      placeholder: |
        Example: "My Scans"
    validations:
      required: true

  - type: input
    id: source-url
    attributes:
      label: Source URL
      placeholder: |
        Example: "https://myscans.manga"
    validations:
      required: true

  - type: textarea
    id: source-language
    attributes:
      label: Source language(s)
      placeholder: |
        Example: "English"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
